修改新手问题中部分描述
HMCL-dev/HMCL-docs pull request #93
Opened 2024-03-09 13:33 UTC by HisAtri

- 部分描述不清的内容
- 部分准确信欠佳的内容

2024-03-09 13:43 UTC, burningtnt commented
HMCL 能够自动检测系统上的 JDK，是否应当鼓励用户使用 HMCL 检测到的 Java，而非手动填入路径？

2024-03-09 13:48 UTC, HisAtri commented
> HMCL 能够自动检测系统上的 JDK，是否应当鼓励用户使用 HMCL 检测到的 Java，而非手动填入路径？

文档里的是选择非全局Java版本，包括自行下载或编译的JDK。

我这里的修改是
```
 > 进入 设置-->全局游戏设置-->Java路径--->选择自定义并找到你需要的 jdk 的路径后确定
+> 选择的 JDK 一般为您的Java安装路径下的`bin\java.exe`(Windows)或`bin/java`(Linux/Unix)
```

2024-03-14 12:50 UTC, burningtnt requested changes

2024-03-14 12:50 UTC, burningtnt commented on _docs/about-questions.md
> +> 选择的 JDK 一般为您的Java安装路径下的`bin\java.exe`(Windows)或`bin/java`(Linux/Unix)
应当鼓励玩家使用 HMCL 检测到的 Java。

2024-03-14 12:50 UTC, burningtnt commented on _docs/about-questions.md
> +- [JAVA 8](https://www.java.com/en/download/) 可用于 Minecraft 1.15 以前的版本
请推荐 Bellsoft JRE Full 8，否则可能导致 HMCL 缺失 JavaFX 无法启动
https://bell-sw.com/pages/downloads/#jdk-8-lts

2024-03-15 01:04 UTC, burningtnt commented on _docs/about-questions.md
> +- [JAVA 8](https://www.java.com/en/download/) 可用于 Minecraft 1.15 以前的版本
请问你有什么以为吗？

2024-03-15 01:06 UTC, HisAtri commented on _docs/about-questions.md
> +> 选择的 JDK 一般为您的Java安装路径下的`bin\java.exe`(Windows)或`bin/java`(Linux/Unix)
所以为什么要在“教玩家如何自己选择JAVA版本”的地方鼓励其使用自动检查的JAVA

2024-03-15 01:38 UTC, burningtnt commented on _docs/about-questions.md
> +> 选择的 JDK 一般为您的Java安装路径下的`bin\java.exe`(Windows)或`bin/java`(Linux/Unix)
应鼓励玩家从下面 HMCL 扫到的 java 里选一个，而不是走自定义

2024-04-07 14:46 UTC, burningtnt commented
- 请引导玩家先进入特定游戏设置，发现没有启用特定游戏设置后再进入全局设置
- Java 版本推荐有误。1.16.5 以及下需要用 Java 8，1.17 - 1.17.1 要用 Java 16，1.18 以上要用 Java 17；对于最新的 Java 21 要求可以先不写进手册。
- 请不要移除训练新手阅读黑体文本的内容，这很有用

2024-04-07 15:10 UTC, closed without merging

2024-04-07 15:10 UTC, HisAtri commented
1. 我不认为“**想必你注意到我了，记住上面讲的话**”是什么意旨明确的描述，它也不应当出现于任何官方文档中。这仅是我的个人看法。
2. 此Pr的目的就是在保留原文结构和语义的基础上，修正其中描述不清或存在偏差的内容。这就是此PR的生命周期的任务。
3. 更多内容的添加和更多细节的完善，原则上应该由独立的正式PR完成。希望通过此PR添加亦非不可，但请一次性地完整地提出修改要求，而不是需要我去“维护一个PR”。